version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./database:/var/lib/postgresql/data
  seq:
    image: datalust/seq:latest
    restart: on-failure
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 5340:80