version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./database:/var/lib/postgresql/data
  seq:
    image: datalust/seq:latest
    restart: on-failure
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 5340:80
  jaeger:
    image: jaegertracing/all-in-one
    restart: on-failure
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686      